<a href="https://colab.research.google.com/github/IAMLATI/Demo-Repo2/blob/master/RNN_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install tensorflow

In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent=[
    "the glass of milk",
    "the glass of Juice",
    "the cup of tea",
    "I am a good boy",
    "I am a good developer",
    "Understand the meaning of words",
    "Your videos are good"
]

In [4]:
## define the vocabulary size
voc_size=10000


In [5]:
 ### One hot representation
one_hot_repr= [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[9217, 4460, 5953, 7610],
 [9217, 4460, 5953, 8722],
 [9217, 8729, 5953, 443],
 [1296, 3601, 1506, 2771, 900],
 [1296, 3601, 1506, 2771, 2576],
 [3812, 9217, 3657, 5953, 4048],
 [1332, 454, 7476, 2771]]

In [6]:
## word embedding repr

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
sent_length=8
embeeded_docs=pad_sequences(one_hot_repr, padding= 'pre', maxlen= sent_length)

In [8]:
print(embeeded_docs)

[[   0    0    0    0 9217 4460 5953 7610]
 [   0    0    0    0 9217 4460 5953 8722]
 [   0    0    0    0 9217 8729 5953  443]
 [   0    0    0 1296 3601 1506 2771  900]
 [   0    0    0 1296 3601 1506 2771 2576]
 [   0    0    0 3812 9217 3657 5953 4048]
 [   0    0    0    0 1332  454 7476 2771]]


In [9]:
## feature repr
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')
model.build(input_shape=(None, sent_length))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.predict(embeeded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step


array([[[ 0.00311605,  0.02793715, -0.0459164 , -0.04346844,
         -0.00368387, -0.02583687, -0.00252583,  0.04178487,
         -0.02400442,  0.03292282],
        [ 0.00311605,  0.02793715, -0.0459164 , -0.04346844,
         -0.00368387, -0.02583687, -0.00252583,  0.04178487,
         -0.02400442,  0.03292282],
        [ 0.00311605,  0.02793715, -0.0459164 , -0.04346844,
         -0.00368387, -0.02583687, -0.00252583,  0.04178487,
         -0.02400442,  0.03292282],
        [ 0.00311605,  0.02793715, -0.0459164 , -0.04346844,
         -0.00368387, -0.02583687, -0.00252583,  0.04178487,
         -0.02400442,  0.03292282],
        [ 0.04965105, -0.0075459 ,  0.04889207,  0.04818786,
          0.02832346, -0.00881125, -0.03932878,  0.04498998,
          0.02867362,  0.04613357],
        [ 0.03215614, -0.03477772, -0.01776636,  0.02353549,
         -0.03469773, -0.02311865, -0.00245154,  0.01628134,
          0.01521396,  0.01987398],
        [ 0.02955851,  0.00954564,  0.01632711, -0.0

In [15]:
embeeded_docs[0]

array([   0,    0,    0,    0, 9217, 4460, 5953, 7610], dtype=int32)

In [19]:
model.predict(embeeded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step


array([[[ 0.00311605,  0.02793715, -0.0459164 , -0.04346844,
         -0.00368387, -0.02583687, -0.00252583,  0.04178487,
         -0.02400442,  0.03292282],
        [ 0.00311605,  0.02793715, -0.0459164 , -0.04346844,
         -0.00368387, -0.02583687, -0.00252583,  0.04178487,
         -0.02400442,  0.03292282],
        [ 0.00311605,  0.02793715, -0.0459164 , -0.04346844,
         -0.00368387, -0.02583687, -0.00252583,  0.04178487,
         -0.02400442,  0.03292282],
        [ 0.00311605,  0.02793715, -0.0459164 , -0.04346844,
         -0.00368387, -0.02583687, -0.00252583,  0.04178487,
         -0.02400442,  0.03292282],
        [ 0.04965105, -0.0075459 ,  0.04889207,  0.04818786,
          0.02832346, -0.00881125, -0.03932878,  0.04498998,
          0.02867362,  0.04613357],
        [ 0.03215614, -0.03477772, -0.01776636,  0.02353549,
         -0.03469773, -0.02311865, -0.00245154,  0.01628134,
          0.01521396,  0.01987398],
        [ 0.02955851,  0.00954564,  0.01632711, -0.0

In [22]:
import numpy as np

# Ensure the input is shaped as (1, 8)
input_sample = np.array([embeeded_docs[0]])  # shape: (1, 8)

# Predict
embedding = model.predict(input_sample)

# Check shape and view output
print("Embedding shape:", embedding.shape)  # (1, 8, 10)
print("Embedding for each word:\n", embedding[0])  # (8, 10)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step
Embedding shape: (1, 8, 10)
Embedding for each word:
 [[ 0.00311605  0.02793715 -0.0459164  -0.04346844 -0.00368387 -0.02583687
  -0.00252583  0.04178487 -0.02400442  0.03292282]
 [ 0.00311605  0.02793715 -0.0459164  -0.04346844 -0.00368387 -0.02583687
  -0.00252583  0.04178487 -0.02400442  0.03292282]
 [ 0.00311605  0.02793715 -0.0459164  -0.04346844 -0.00368387 -0.02583687
  -0.00252583  0.04178487 -0.02400442  0.03292282]
 [ 0.00311605  0.02793715 -0.0459164  -0.04346844 -0.00368387 -0.02583687
  -0.00252583  0.04178487 -0.02400442  0.03292282]
 [ 0.04965105 -0.0075459   0.04889207  0.04818786  0.02832346 -0.00881125
  -0.03932878  0.04498998  0.02867362  0.04613357]
 [ 0.03215614 -0.03477772 -0.01776636  0.02353549 -0.03469773 -0.02311865
  -0.00245154  0.01628134  0.01521396  0.01987398]
 [ 0.02955851  0.00954564  0.01632711 -0.03447504  0.03799457 -0.03873
  -0.02481988 -0.03900773 -0.00029997 -0.04535145]
 [-0.00228222 -0.03782828 -0.0419953